# Site settings
title: Liz's Jekyll Test
email: eashigetoshi@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  Testing this for work. :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lshig.github.io" # the base hostname & protocol for your site
twitter_username: LizShigetoshi
github_username:  lshig

# Build settings
markdown: kramdown
