markdown: kramdown
kramdown:
  input: GFM
title: Liz Shigetoshi
description: "Hi, I'm Liz Shigetoshi. Full Stack Developer fueled by a daily dose of 150+ mg of caffeine and 150+ g of carbs drenched in hot sauce."
email: lizshigetoshi@gmail.com
baseurl: ""
url: "http://lizshigetoshi.com"
timezone: America/Sacramento
author: Liz Shigetoshi
github_username:  lshig
medium_username: lizshigetoshi
instagram_username: lizshig
facebook_username: shigetoshi
linkedin_username: elizabethshigetoshi
gems:
  - jemoji
